theme: jekyll-theme-clean-blog
Title: "Jared's Blog Site"
Description: This blog will be updated weekly and is intended to document my journey into web development and Python. Please bookmark if you would like to follow along.
